apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangodatabases.databaseadmin.arangodb.com
spec:
  group: databaseadmin.arangodb.com
  names:
    kind: ArangoDatabase
    listKind: ArangoDatabaseList
    plural: arangodatabases
    shortNames:
    - arangodbase
    singular: arangodatabase
  scope: Namespaced
  version: v1alpha

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangousers.databaseadmin.arangodb.com
spec:
  group: databaseadmin.arangodb.com
  names:
    kind: ArangoUser
    listKind: ArangoUserList
    plural: arangousers
    shortNames:
    singular: arangouser
  scope: Namespaced
  version: v1alpha

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangocollections.databaseadmin.arangodb.com
spec:
  group: databaseadmin.arangodb.com
  names:
    kind: ArangoCollection
    listKind: ArangoCollectionList
    plural: arangocollections
    shortNames:
    singular: arangocollection
  scope: Namespaced
  version: v1alpha

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangographs.databaseadmin.arangodb.com
spec:
  group: databaseadmin.arangodb.com
  names:
    kind: ArangoGraph
    listKind: ArangoGraphList
    plural: arangographs
    shortNames:
    singular: arangograph
  scope: Namespaced
  version: v1alpha
