apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangodeployments.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoDeployment
    listKind: ArangoDeploymentList
    plural: arangodeployments
    shortNames:
    - arangodb
    - arango
    singular: arangodeployment
  scope: Namespaced
  version: v1alpha
